final Map<String, String> English = {
  "about_us": "About us",
  "add_bookmark": "Add Bookmark",
  "add_new_method": "Add New Method",
  "add_new_vehicle": "Add New Vehicle",
  "add_to_favorites": "Add to Favorites",
  "alerts": "Alerts",
  "already_a_member": "Already a member",
  "are_you_sure": "Are you sure?",
  "are_you_sure_logout": "Are your sure you want to log out?",
  "back_to_login": "Back to Login",
  "book_now": "Book Now",
  "bookings": "Bookings",
  "buy_a_wash": "Buy A Wash",
  "call": "Call",
  "cancel": "Cancel",
  "captai's_ceramic": "Captai's Ceramic",
  "captains_ceramic": "Captain's Ceramic",
  "change_language": "Change Language",
  "change_password": "Change password",
  "change": "Change?",
  "chats": "Chats",
  "code_incorrect": "Code Incorrect",
  "comments": "COMMENTS",
  "complete_interior_clean": "Complete Interior Clean",
  "contact_us": "Contact Us",
  "continue": "Continue",
  "copy_link": "Copy Link",
  "create_password": "Create Password",
  "create_new_password": "Create New Password",
  "create_account_continue": "Create an account to continue.",
  "credit_debit_card": "Credit or Debit Card",
  "delete_my_account": "Delete my account",
  "deluxe_interior_cleaning": "Deluxe Interior Cleaning",
  "details": "Details",
  "directions": "Directions",
  "dirty_dog's_car_wash_kennesaw": "Dirty Dog's Car Wash Kennesaw",
  "app_slogan": "Welcome to Dirty Dog's Car Wash.\n First in Service. First in Community",
  "dont_have_account": "Don't have an account? ",
  "email_address": "EMAIL ADDRESS",
  "edit_actions": "Edit Actions...",
  "edit_profile": "Edit Profile",
  "Email_Address": "Email Address",
  "email_notifications": "Email Notifications",
  "engine_bay_detailing": "Engine Bay Detailing",
  "enter_code": "Enter the code sent to your phone to continue.",
  "exclusive_offers": "Exclusive Offers\nonly available on the App",
  "faqs": "FAQ’s",
  "first_name": "FIRST NAME",
  "feedback": "Feedback",
  "find_details": "Find details about our automated wash process...",
  "find_on_page": "Find on Page",
  "first_Last": "First Last",
  "first_in_service_first_in_community": "First in Service. First in Community.",
  "forgot_password": "Forgot password?",
  "give_rating": "Give Rating",
  "glass_cleaner": "Glass Cleaner",
  "group": "Group",
  "hOW_dID_yOU_hEAR_aBOUT_uS": "HOW DID YOU HEAR ABOUT US?",
  "heat_and_blow_dry": "Heat and Blow Dry",
  "hello_my_friend!": "Hello, my friend!",
  "help": "Help",
  "home": "Home",
  "hot_wax": "Hot Wax",
  "i_accept_terms": "I accept the",
  "terms_condition": " terms and conditions",
  "id": "ID",
  "interior_detail_spray": "Interior Detail Spray",
  "introduction": "Introduction",
  "join_our_wash_memberships_for": "Join Our\nWash Memberships for",
  "amazing_perks": "Amazing Perks!",
  "last_name": "Last Name",
  "lava_shield": "Lava Shield",
  "liam_gotham": "Liam Gotham",
  "license_plate": "LICENSE PLATE",
  "limited_wash_membership": "Limited Wash Membership",
  "location": "Location",
  "locations": "Locations",
  "log_in_continue": "Log in to your account to continue.",
  "logging_out": "Logging out?",
  "login": "Login",
  "manage_bookings": "Manage Bookings",
  "menu": "Menu",
  "mercedes_blue": "Mercedes / Blue",
  "message": "Message",
  "model": "MODEL",
  "my_codes": "My Codes",
  "my_code": "MyCodes",
  "my_account": "My account",
  "nearest_location": "Nearest Location? ",
  "nearest_location1": "Use my Location",
  "no_extra_fees_for_cancelling_or_rescheduling_the_appointments.": "No extra fees for cancelling or rescheduling the appointments.",
  "not_now": "Not now",
  "ok": "OK",
  "one_time": "One-time",
  "or_continue_with": "Or continue with",
  "password": "Password",
  "password_updated": "Password Updated",
  "paypal": "PayPal",
  "pending": "Pending",
  "phasellus_eleifend_feugiat_felis": "Phasellus eleifend feugiat felis...",
  "phone_number": "Phone Number",
  "platinum_detailing": "Platinum Detailing",
  "price": "Price: \$20",
  "prime_low_pH_conditioner": "Prime Low PH Conditioner",
  "proceed_to_payment": "Proceed to payment",
  "profile": "Profile",
  "purchase_wash": "Purchase a wash",
  "push_notifications": "Push Notifications",
  "retype_password": "RETYPE NEW PASSWORD",
  "rain_repel": "Rain Repel",
  "rate_your_experience": "Rate your experience",
  "refer_a_friend": "Refer a friend",
  "remove_valuables": "Remove valuables..",
  "replace_photo": "Replace Photo",
  "retype_Password": "Retype Password",
  "rookie": "Rookie",
  "sMS_notifications": "SMS Notifications",
  "save": "Save",
  "save_changes": "Save changes",
  "save_with_our_memberships": "Membership Savings",
  "scan_your_code": "Scan your code...",
  "search": "Search",
  "select_language": "Select Language",
  "select_location": "Select location",
  "select_state": "Select state",
  "send_code_again": "Send Code Again :54",
  "service": "Service",
  "services": "Services",
  "settings": "Settings",
  "sign_in": "Sign In",
  "sign_up": "Sign Up",
  "sign_in_google": "Sign in with Google",
  "size": "Size",
  "social_media": "Social Media",
  "soft_tops_custom_parts_not_covered": "Soft tops & custom parts not covered...",
  "start": "Start",
  "state": "STATE",
  "submit": "Submit",
  "sunday_17_jan": "Sunday, 17 Jan",
  "terms_of_use": "Terms of Use",
  "tesla": "Tesla",
  "teslaWhite": "Tesla / White",
  "thursday_14_jan": "Thursday, 14 Jan",
  "tip": "Tip",
  "tire_dressing": "Tire Dressing",
  "tire_shine": "Tire Shine",
  "toyota": "Toyota",
  "triple_foam": "Triple Foam",
  "unlimited_4_alarm_graphene": "Unlimited 4 Alarm Graphene",
  "unlimited_captain_ceramic": "Unlimited Captain's Ceramic",
  "unlimited_membership": "Unlimited Wash Membership",
  "update": "Update",
  "use_my_location": "Use my Location",
  "vehicles": "Vehicles",
  "verify_phone_number": "Verify Your Phone Number",
  "view_qr_code": "View QR Code",
  "view_rating": "View Rating",
  "wash_packages": "Wash Packages",
  "wash_history": "Wash history",
  "wheel_polish": "Wheel Polish",
  "write_message": "Write a message...",
  "yes_delete": "Yes, delete",
  "logout": "Yes, log me out",
  "password_changed": "Your password has been successfully changed.",
  "already_have_an_account": "Already have an account? ",
  "didn't_receive_the_code": "Didn't receive the code? ",
  "resend": "Resend",
  "Choose_strong_password": "Choose strong password to secure your account.",
  "code_incorrect_try_again": "The code entered is incorrect. Please try again.",
  "payment_methods": "Payment Methods",
  "Alarm_Graphene": "4 Alarm Graphene",
  "helping_heroes": "Helping Heroes",
  "last_week": "Last Week",
  "today": "Today",
  "completed": "Completed",
  "privacy_policy": "Privacy Policy",
  "profile_photo": "Profile Photo",
  "general_information": "General Information",
  "make": "MAKE",
  "color": "COLOR",
  "year": "YEAR",
  "type_password": "TYPE PASSWORD",
  "hand_car_wash": "5 Star Hand Car Wash",
  "damage": "Soft tops & custom parts not covered for damage. \n Remove valuables; we are not liable for loss.",
  "full_exterior_polish": "Full Exterior Polish",
  "ceramic_coating_application": "Ceramic Coating Application",
  "sure_delete_account": "Are you sure you want to delete your account?",
  "add_to_reading_list": "Add to Reading List",
  "logout1": "Logout",
  "extra_appointment": "No extra fees for cancelling or rescheduling the appointments.",
  "booking_status": "Booking Status",
  "submitted": "Submitted",
  "reschedule": "Reschedule",
  "best": "Best",
  "good": "Good",
  "neutral": "Neutral",
  "bad": "Bad",
  "worst": "Worst",
  "app_Navigation_Tips": "App Navigation Tips",
};
