final Map<String, String> Spanish = {
  "about_us": "Sobre nosotros",
  "add_bookmark": "Añadir marcador",
  "add_new_method": "Agregar nuevo método",
  "add_new_vehicle": "Agregar nuevo vehículo",
  "add_to_favorites": "Agregar a favoritos",
  "alerts": "Alertas",
  "already_a_member": "Ya eres miembro?",
  "are_you_sure": "Estás seguro?",
  "are_you_sure_logout": "Estás seguro de que deseas cerrar sesión?",
  "back_to_login": "Volver al inicio de sesión",
  "book_now": "Reservar ahora",
  "bookings": "Reservas",
  "buy_a_wash": "Comprar un lavado",
  "call": "Llamar",
  "cancel": "Cancelar",
  "captai's_ceramic": "Cerámica de Captai",
  "captains_ceramic": "Cerámica del Capitán",
  "change_language": "Cambiar idioma",
  "change_password": "Cambiar contraseña",
  "change": "Cambiar?",
  "chats": "charlas",
  "code_incorrect": "Código incorrecto",
  "color": "Color",
  "comments": "Comentarios",
  "complete_interior_clean": "Limpieza interior completa",
  "contact_us": "Contáctanos",
  "continue": "Continuar",
  "copy_link": "Copiar enlace",
  "create_password": "Crear contraseña",
  "create_new_password": "Crear nueva contraseña",
  "create_account_continue": "Crea una cuenta para continuar.",
  "credit_debit_card": "Tarjeta de crédito o débito",
  "delete_my_account": "Eliminar mi cuenta",
  "deluxe_interior_cleaning": "Limpieza interior de lujo",
  "details": "Detalles",
  "directions": "Indicaciones",
  "dirty_dog's_car_wash_kennesaw": "Dirty Dog's Car Wash Kennesaw",
  "app_slogan": "Dirty Dog's Car Wash. Líder en servicio y comunidad",
  "dont_have_account": "No tienes una cuenta? ",
  "email_address": "DIRECCIÓN DE CORREO ELECTRÓNICO",
  "edit_actions": "Editar acciones...",
  "edit_profile": "Editar perfil",
  "Email_Address": "Dirección de correo electrónico",
  "email_notifications": "Notificaciones por correo",
  "engine_bay_detailing": "Detallado del compartimento del motor",
  "enter_code": "Ingresa el código enviado a tu teléfono para continuar.",
  "exclusive_offers": "Ofertas exclusiva solo \ndisponibles en la aplicación",
  "faqs": "Preguntas frecuentes",
  "first_name": "NOMBRE",
  "feedback": "Comentarios",
  "find_details": "Encuentra detalles sobre nuestro proceso de lavado automático...",
  "find_on_page": "Buscar en la página",
  "first_Last": "Nombre Apellido",
  "first_in_service_first_in_community": "Líder en servicio. Líder en comunidad.",
  "forgot_password": "Olvidaste tu contraseña?",
  "give_rating": "Dar calificación",
  "glass_cleaner": "Limpiador de vidrios",
  "group": "Grupo",
  "hOW_dID_yOU_hEAR_aBOUT_uS": "CÓMO TE ENTERASTE DE NOSOTROS?",
  "heat_and_blow_dry": "Calor y secado con aire",
  "hello_my_friend!": "¡Hola, amigo mío!",
  "help": "Ayuda",
  "home": "Inicio",
  "hot_wax": "Cera caliente",
  "i_accept_terms": "Acepto los ",
  "terms_condition": "términos y condiciones",
  "id": "Identificación",
  "interior_detail_spray": "Aerosol para detalles interiores",
  "introduction": "Introducción",
  "join_our_wash_memberships_for": "¡Únete a nuestras\n membresías de lavado para\n",
  "amazing_perks": "increíbles beneficios!",
  "last_name": "Apellido",
  "lava_shield": "Escudo de lava",
  "liam_gotham": "Liam Gotham",
  "license_plate": "Placa de matrícula",
  "limited_wash_membership": "Membresía de lavado limitada",
  "location": "Ubicación",
  "locations": "Ubicaciones",
  "log_in_continue": "Inicia sesión en tu cuenta para continuar.",
  "logging_out": "Cerrar sesión?",
  "login": "Iniciar sesión",
  "manage_bookings": "Gestionar reservas",
  "menu": "Menú",
  "mercedes_blue": "Mercedes / Azul",
  "message": "Mensaje",
  "model": "Modelo",
  "my_codes": "Mis códigos",
  "my_code": "Mis códigos",
  "my_account": "Mi cuenta",
  "nearest_location": "Ubicación más cercana? ",
  "nearest_location1": "Usar mi ubicación",
  "no_extra_fees_for_cancelling_or_rescheduling_the_appointments.": "Sin cargos adicionales por cancelar o reprogramar citas.",
  "not_now": "Ahora no",
  "ok": "OK",
  "one_time": "Único",
  "or_continue_with": "O continuar con",
  "password": "Contraseña",
  "password_updated": "Contraseña actualizada",
  "paypal": "PayPal",
  "pending": "Pendiente",
  "phasellus_eleifend_feugiat_felis": "Phasellus eleifend feugiat felis...",
  "phone_number": "Número de teléfono",
  "platinum_detailing": "Detallado platino",
  "price": "Precio: \$20",
  "prime_low_pH_conditioner": "Acondicionador Prime de bajo pH",
  "proceed_to_payment": "Proceder al pago",
  "profile": "Perfil",
  "purchase_wash": "Comprar un lavado",
  "push_notifications": "Notificaciones push",
  "retype_password": "REPITE LA NUEVA CONTRASEÑA",
  "rain_repel": "Repelente de lluvia",
  "rate_your_experience": "Califica tu experiencia",
  "refer_a_friend": "Recomienda a un amigo",
  "remove_valuables": "Retira los objetos de valor...",
  "replace_photo": "Reemplazar foto",
  "retype_Password": "Reescribir contraseña",
  "rookie": "Novato",
  "sMS_notifications": "Notificaciones por SMS",
  "save": "Guardar",
  "save_changes": "Guardar cambios",
  "save_with_our_memberships": "ver membresías",
  "scan_your_code": "Escanea tu código...",
  "search": "Buscar",
  "select_language": "Seleccionar idioma",
  "select_location": "Seleccionar ubicación",
  "select_state": "Seleccionar estado",
  "send_code_again": "Enviar código de nuevo :54",
  "service": "Servicio",
  "services": "Servicios",
  "settings": "Configuración",
  "sign_in": "Iniciar sesión",
  "sign_up": "Regístrate",
  "sign_in_google": "Inicia sesión con Google",
  "size": "Tamaño",
  "social_media": "Redes sociales",
  "soft_tops_custom_parts_not_covered": "Capotas blandas y piezas personalizadas no cubiertas...",
  "start": "Comenzar",
  "state": "Estado",
  "submit": "Enviar",
  "sunday_17_jan": "Domingo, 17 de enero",
  "terms_of_use": "Términos de uso",
  "tesla": "Tesla",
  "teslaWhite": "Tesla / Blanco",
  "thursday_14_jan": "Jueves, 14 de enero",
  "tip": "Propina",
  "tire_dressing": "Abrillantador de llantas",
  "tire_shine": "Brillo para llantas",
  "toyota": "Toyota",
  "triple_foam": "Espuma triple",
  "unlimited_4_alarm_graphene": "Graphene 4 Alarm Ilimitado",
  "unlimited_captain_ceramic": "Cerámica del Capitán Ilimitada",
  "unlimited_membership": "Membresía de lavado ilimitada",
  "update": "Actualizar",
  "use_my_location": "Usar mi ubicación",
  "vehicles": "Vehículos",
  "verify_phone_number": "Verifica tu número de teléfono",
  "view_qr_code": "Ver código QR",
  "view_rating": "Ver calificación",
  "wash_packages": "Paquetes de lavado",
  "wash_history": "Historial de lavado",
  "wheel_polish": "Pulido de ruedas",
  "write_message": "Escribe un mensaje...",
  "yes_delete": "Sí, eliminar",
  "logout": "Sí, cerrar sesión",
  "password_changed": "Tu contraseña se ha cambiado exitosamente.",
  "already_have_an_account": "Ya tienes una cuenta? ",
  "didn't_receive_the_code": "No recibiste el código?",
  "resend": "Reenviar",
  "Choose_strong_password": "Elija una contraseña segura para proteger su cuenta.",
  "code_incorrect_try_again": "El código introducido es incorrecto. Inténtalo de nuevo.",
  "payment_methods": "Métodos de pago",
  "Alarm_Graphene": "4 Alarma Grafeno",
  "helping_heroes": "Ayudando a los héroes",
  "last_week": "La semana pasada",
  "today": "Hoy",
  "completed": "Terminada",
  "privacy_policy": "política de privacidad",
  "profile_photo": "Foto de perfil",
  "general_information": "Información general",
  "make": "HACER",
  "color": "COLOR",
  "year": "AÑO",
  "type_password": "ESCRIBA LA CONTRASEÑA",
  "hand_car_wash": "Lavado de autos a mano 5 estrellas",
  "damage": "Las capotas blandas y las piezas personalizadas no están cubiertas por daños. \n Retire los objetos de valor; no nos hacemos responsables de pérdidas.",
  "full_exterior_polish": "Pulido exterior completo",
  "ceramic_coating_application": "Aplicación de revestimiento cerámico",
  "sure_delete_account": "Estás segura de que quieres eliminar tu cuenta?",
  "add_to_reading_list": "Agregar a la lista de lectura",
  "logout1": "Cerrar sesión",
  "extra_appointment": "No hay cargos extra por cancelar o reprogramar las citas.",
  "booking_status": "Estado de la reserva",
  "submitted": "Enviada",
  "reschedule": "Reprogramar",
  "best": "La mejor",
  "good": "Buena",
  "neutral": "Neutral",
  "bad": "Mala",
  "worst": "El peor",
  "app_Navigation_Tips": "navegación de la aplicación"

};